part of flutter_image_filters;

Map<Type, Future<FragmentProgram> Function()> _fragmentPrograms = {
  MonochromeShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/monochrome.frag'),
  SquareLookupTableShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/lookup.frag'),
  HALDLookupTableShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/hald_lookup.frag'),
  BrightnessShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/brightness.frag'),
  ZoomBlurShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/zoom_blur.frag'),
  WhiteBalanceShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/white_balance.frag'),
  VignetteShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/vignette.frag'),
  VibranceShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/vibrance.frag'),
  ContrastShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/contrast.frag'),
  HueShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/hue.frag'),
  SwirlShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/swirl.frag'),
  SolarizeShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/solarize.frag'),
  SaturationShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/saturation.frag'),
  RGBShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/rgb.frag'),
  PosterizeShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/posterize.frag'),
  PixelationShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/pixelation.frag'),
  OpacityShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/opacity.frag'),
  LuminanceShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/luminance.frag'),
  LuminanceThresholdShaderConfiguration: () =>
      FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/luminance_threshold.frag'),
  KuwaharaShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/kuwahara.frag'),
  HighlightShadowShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/highlight_shadow.frag'),
  BulgeDistortionShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/bulge_distortion.frag'),
  CGAColorspaceShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/cga_colorspace.frag'),
  ColorInvertShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/color_invert.frag'),
  ColorMatrixShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/color_matrix.frag'),
  CrosshatchShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/crosshatch.frag'),
  ExposureShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/exposure.frag'),
  FalseColorShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/false_color.frag'),
  GammaShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/gamma.frag'),
  GrayscaleShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/grayscale.frag'),
  GlassSphereShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/glass_sphere.frag'),
  HalftoneShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/halftone.frag'),
  HazeShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/haze.frag'),
  NoneShaderConfiguration: () => FragmentProgram.fromAsset('packages/flutter_image_filters/shaders/none.frag'),
};
